### PR TITLE
Nawqaan 359

### PR DESCRIPTION
**Pull request by mbucknell**
Added three health service urls.

### CODE REVIEW

**Comment by cschroed-usgs** [comment]
This implementation looks good. I'm not sure that the SA's monitoring system supports multiple health endpoints, but I think we should :shipit: and see how the integration with their tools goes.

**Comment by cschroed-usgs** [comment]
Here's an example of a single-endpoint health check for cch:
http://cida.usgs.gov/coastalchangehazardsportal/data/health

**Comment by mbucknell** [comment]
We can pretty easily convert, but I also like the separate health checks. Otherwise, what do you do if one is down? Do you still return a 200 response with the json object reflecting the issue. Guess I need to talk to the SAs.

**Comment by jiwalker-usgs** [comment]
Thanks for the plug Carl.  I think mon just makes the request and looks for a 200, but I am not totally sure.  Multiple mon jobs can be set up (GDP has like 5).

**Comment by mbucknell** [comment]
Yeah, I just talked to Shirley who thought separate would be find. Tomorrow I'll verify with Brian Higgins.

**Pull request merged**
